development: &default
  adapter: postgresql
  database: krudmin_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: krudmin_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
